version: "3.8"
services:
  mysql:
    image: mysql
    restart: no
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: db

  redis:
    image: redis
    ports:
      - "6379:6379"
